# Generated by Django 4.1.2 on 2022-10-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('buildup_start_date', models.DateField(blank=True)),
                ('event_start_date', models.DateField(blank=True)),
                ('event_end_date', models.DateField(blank=True)),
                ('teardown_end_date', models.DateField(blank=True)),
                ('event_welcome_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Event Config',
                'verbose_name_plural': 'Event Configs',
            },
        ),
    ]
