# Generated by Django 4.1.2 on 2022-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restricted', models.IntegerField()),
                ('description', models.TextField()),
                ('requires_driver_license', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Volunteer Type',
                'verbose_name_plural': 'Volunter Types',
            },
        ),
    ]
