# Generated by Django 4.1.2 on 2022-10-21 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('restricted', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('requires_driver_license', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Volunteer Type',
                'verbose_name_plural': 'Volunter Types',
            },
        ),
    ]
