# Generated by Django 4.1.2 on 2022-10-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_age_user_arrival_user_arrived_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('2xl', '2xl'), ('3xl', '3xl')], default=None, max_length=3, null=True),
        ),
    ]
